### This is a `.properties` [https://en.wikipedia.org/wiki/.properties] file for termux app properties and loaded with  `java.util.Properties.load()`
### To make changes to a property value, uncomment the property line by removing any hash `#` characters at the start of the line
### After making changes, save and run `termux-reload-settings` or reopen the app
### All information here can also be found on the
### wiki: https://wiki.termux.com/wiki/Terminal_Settings



#####
# General
#####
### Allow external app
# allow-external-apps = true

### Default working directory 
# default-working-directory = /data/data/com.termux/files/home

### Toasts display
disable-terminal-session-change-toast = true

### Soft keyboard on start
hide-soft-keyboard-on-startup = true

### Keyboard toggle button to enable or disable software keyboard instead of showing/hiding it.
# soft-keyboard-toggle-behaviour = enable/disable

### terminal scrollback buffer. Max is 50000. May have negative impact on performance.
# terminal-transcript-rows = 2000

### volume keys for adjusting volume and not for the extra keys functionality.
# volume-keys = volume



#####
# Fullscreen mode
#####
### Termux start in full screen mode.
# fullscreen = true

### attempt workaround layout issues when running in ull screen mode.
# use-fullscreen-workaround = true



#####
# Cursor
#####
# terminal-cursor-blink-rate = 0
# terminal-cursor-style = block



#####
# Terminal Session
#####
### shorrcut session and terminal
shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 1
# shortcut.rename-session = ctrl + n


#####
# Terminal Margin
### Horizontal and Vertical Margin
# terminal-margin-horizontal=3
# terminal-margin-vertical=0
#####



#####
# Extra keys
#####
### Choose default, arrows-only, arrows-all, all and none
# extra-keys-style = default

### capitalize all text in extra keys row button labels.
# extra-keys-text-all-caps = true

### Configuration with additional popup keys (swipe up)
extra-keys = [ \
 [ \
    { "key": "CTRL", "popup": {"key": "ALT"}}, \
    { "macro": "CTRL C", "display": "STOP"}, \
    { "key": "~", "popup": {"key": "-"}}, \
    { "key": "PASTE", "display": "PASTE"}, \
    { "macro": "cd", "display": "cd", "popup": {"macro": ".."}}, \
    { "key": "UP"}, \
    { "macro": "CTRL D", "display": "LOGOUT"} \
 ], \
 [ \
    { "macro": "clear\n", "display": "clear"}, \
    { "key": "END", "popup": {"key": "HOME"}}, \
    { "key": "*", "popup": {"key": "."}}, \
    { "macro": "CTRL T", "display": "NEW"}, \
    { "key": "LEFT"}, \
    { "key": "ENTER", "display": "•"}, \
    { "key": "RIGHT"} \
 ], \
 [ \
    { "macro": "CTRL X", "display": "exit"}, \
    { "macro": "ALT R", "display": "SSH"}, \
    { "key": "/", "popup": {"key": "\\\\"}},  \
    { "macro": "CTRL 2", "display": "NEXT", "popup": {"key": "CTRL 1"}}, \
    { "macro": "ls\n", "display": "ls"}, \
    { "key": "DOWN"}, \
    { "macro": "ubuntu\n", "display": "LOGIN"} \
 ] \
]
