name: Run AdsCoin Manual

on:
  workflow_dispatch:

jobs:
  run-adscoin:
    runs-on: ubuntu-latest
    name: Manual PHP Runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: PHP Syntax Check
        run: php -l adscoin.php

      - name: Jalankan adscoin.php
        run: php adscoin.php
